"""Create repository-local files used by the AppRC example CLIs."""

from __future__ import annotations

# == Standard Library ========================
import argparse
import json
import shutil
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING

ROOT = Path(__file__).resolve().parents[3]
EXAMPLE_SRC = ROOT / "examples" / "example_apps" / "src"
EXAMPLE_APP_DISK_FILES_ROOT = ROOT / "examples" / "example_app_disk_files"
SHARED_APPRC_DIRECTORY_NAME = "apprc-directories"

if TYPE_CHECKING:
    from _example_apps_utils import ExampleAppSpec


def bootstrap_example_apps(
    *,
    output_root: Path = EXAMPLE_APP_DISK_FILES_ROOT,
    clean: bool = False,
) -> list[Path]:
    """Create deterministic local files for all example CLIs.

    The generated directories are ignored by the repository. They mirror real
    AppRC file ownership while keeping the developer's actual config home and
    storage roots untouched.

    :param output_root: Directory where generated example disk files live.
    :param clean: Whether to remove existing generated example files first.
    :return: Sourceable ``.env`` files written for each example.
    """
    specs = _example_app_specs()
    if clean:
        _remove_generated_files(output_root=output_root, specs=specs)

    env_files: list[Path] = []
    apprc_directories = output_root / SHARED_APPRC_DIRECTORY_NAME
    for spec in specs:
        env_files.append(
            _bootstrap_one(
                output_root=output_root,
                apprc_directories=apprc_directories,
                spec=spec,
            )
        )
    return env_files


def _remove_generated_files(
    *,
    output_root: Path,
    specs: tuple[ExampleAppSpec, ...],
) -> None:
    """Remove generated children without deleting the output root itself."""
    apprc_directories = output_root / SHARED_APPRC_DIRECTORY_NAME
    if apprc_directories.exists():
        shutil.rmtree(apprc_directories)
    for spec in specs:
        root = output_root / spec.root_name
        if root.exists():
            shutil.rmtree(root)


def _bootstrap_one(
    *,
    output_root: Path,
    apprc_directories: Path,
    spec: ExampleAppSpec,
) -> Path:
    """Create one example sandbox and return its sourceable env file."""
    root = output_root / spec.root_name
    root.mkdir(parents=True, exist_ok=True)
    apprc_dir = apprc_directories / spec.kit.spec.app_id
    apprc_dir.mkdir(parents=True, exist_ok=True)

    user_dotenv = apprc_dir / spec.kit.spec.user_dotenv_filename
    _write_env_layer(
        path=user_dotenv,
        layer="per-user dotenv overrides",
        real_location=(
            "~/.local/share/"
            f"{spec.kit.spec.app_id}/{spec.kit.spec.user_dotenv_filename}"
        ),
        values=spec.app_values,
    )

    storage_root = None
    apprc_toml = apprc_dir / spec.kit.spec.apprc_toml_filename
    if spec.uses_storage:
        storage_root = root / "storages" / spec.storage_name
        storage_root.mkdir(parents=True, exist_ok=True)
        _write_env_layer(
            path=storage_root / spec.kit.spec.storage_dotenv_filename,
            layer="storage-local dotenv overrides",
            real_location=(
                f"<selected storage root>/{spec.kit.spec.storage_dotenv_filename}"
            ),
            values=spec.storage_values or {},
        )
        _write_storage_index(
            path=apprc_toml,
            storage_name=spec.storage_name,
            storage_root=storage_root,
            app_id=spec.kit.spec.app_id,
            apprc_toml_filename=spec.kit.spec.apprc_toml_filename,
        )

    env_path = root / ".env"
    _write_sourceable_env(
        path=env_path,
        spec=spec,
        apprc_dir=apprc_dir,
        storage_root=storage_root,
    )
    return env_path


def _example_app_specs() -> tuple[ExampleAppSpec, ...]:
    """Return dev-only example specs from source or installed examples."""
    example_src_text = str(EXAMPLE_SRC)
    if example_src_text not in sys.path:
        sys.path.insert(0, example_src_text)
    from _example_apps_utils import example_app_specs

    return example_app_specs()


def _write_sourceable_env(
    *,
    path: Path,
    spec: ExampleAppSpec,
    apprc_dir: Path,
    storage_root: Path | None,
) -> None:
    """Write the arbitrary user-owned env file for one example."""
    values = {
        spec.kit.spec.apprc_dir_env_key: str(apprc_dir.resolve()),
        **dict(spec.explicit_values),
    }
    if spec.uses_storage:
        storage_env_key = spec.kit.spec.require_storage_selector_env_key()
        if storage_root is None:
            raise RuntimeError(f"{spec.name} requires a storage root.")
        values[storage_env_key] = spec.storage_name

    comment = [
        "# Generated by python -m apprc_dev.example_apps.bootstrap.",
        "# AppRC layer: explicit env file or shell-exported values.",
        "# AppRC does not choose a location for this file in real apps.",
        "# Source it manually, for example: set -a; source .env; set +a",
        f"# Example command: {spec.kit.spec.config_command_name()} config doctor",
        "",
    ]
    path.write_text(
        "\n".join(comment + _dotenv_lines(values)) + "\n",
        encoding="utf-8",
    )


def _write_env_layer(
    *,
    path: Path,
    layer: str,
    real_location: str,
    values: Mapping[str, str],
) -> None:
    """Write one AppRC-managed dotenv layer with explanatory comments."""
    path.parent.mkdir(parents=True, exist_ok=True)
    comment = [
        "# Generated by python -m apprc_dev.example_apps.bootstrap.",
        f"# AppRC layer: {layer}.",
        f"# Bootstrapped checkout path: {path.resolve()}",
        f"# Real app location: {real_location}",
        "",
    ]
    path.write_text(
        "\n".join(comment + _dotenv_lines(values)) + "\n",
        encoding="utf-8",
    )


def _write_storage_index(
    *,
    path: Path,
    storage_name: str,
    storage_root: Path,
    app_id: str,
    apprc_toml_filename: str,
) -> None:
    """Write named-storage AppRC TOML with explanatory comments."""
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(
        [
            "# Generated by python -m apprc_dev.example_apps.bootstrap.",
            "# AppRC layer: named-storage AppRC TOML.",
            f"# Bootstrapped checkout path: {path.resolve()}",
            f"# Real app location: ~/.local/share/{app_id}/{apprc_toml_filename}",
            "",
            f"selected_storage = {json.dumps(storage_name)}",
            "",
            f"[storages.{storage_name}]",
            f"root = {json.dumps(str(storage_root.resolve()))}",
            "",
        ]
    )
    path.write_text(text, encoding="utf-8")


def _dotenv_lines(values: Mapping[str, str]) -> list[str]:
    """Return deterministic dotenv assignment lines."""
    return [
        f"{key}={json.dumps(value)}" for key, value in sorted(values.items())
    ]


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments for the bootstrap helper.

    :param argv: Optional argument vector used by tests.
    :return: Parsed command namespace.
    """
    parser = argparse.ArgumentParser(
        description="Bootstrap repository-local AppRC example app files.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove existing example sandboxes before writing files.",
    )
    parser.add_argument(
        "--output-root",
        "--repo-root",
        dest="output_root",
        type=Path,
        default=EXAMPLE_APP_DISK_FILES_ROOT,
        help="Directory where ignored example disk files are written.",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Run the example bootstrap helper.

    :param argv: Optional argument vector used by tests.
    :return: Process exit code.
    """
    args = parse_args(argv)
    env_files = bootstrap_example_apps(
        output_root=args.output_root,
        clean=args.clean,
    )
    print("Bootstrapped AppRC example files:")
    for env_file in env_files:
        print(f"  {env_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
