"""Create repository-local files used by the AppRC example CLIs."""

from __future__ import annotations

# == Standard Library ========================
import argparse
import json
import shutil
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING

ROOT = Path(__file__).resolve().parents[3]
EXAMPLE_SRC = ROOT / "examples" / "example_apps" / "src"

if TYPE_CHECKING:
    from apprc_example_apps import ExampleAppSpec


def bootstrap_example_apps(
    *,
    repo_root: Path = ROOT,
    clean: bool = False,
) -> list[Path]:
    """Create deterministic local files for all example CLIs.

    The generated directories are ignored by the repository. They mirror real
    AppRC file ownership while keeping the developer's actual config home and
    storage roots untouched.

    :param repo_root: Repository root where sandbox directories should live.
    :param clean: Whether to remove existing example sandboxes first.
    :return: Sourceable ``.env`` files written for each example.
    """
    env_files: list[Path] = []
    for spec in _example_app_specs():
        root = repo_root / spec.root_name
        if clean and root.exists():
            shutil.rmtree(root)
        env_files.append(_bootstrap_one(root=root, spec=spec))
    return env_files


def _bootstrap_one(*, root: Path, spec: ExampleAppSpec) -> Path:
    """Create one example sandbox and return its sourceable env file."""
    root.mkdir(parents=True, exist_ok=True)
    xdg_config_home = root / "xdg-config-home"
    config_home = xdg_config_home / spec.kit.spec.app_name
    config_home.mkdir(parents=True, exist_ok=True)

    app_wide_env = config_home / spec.kit.spec.app_wide_env_filename
    _write_env_layer(
        path=app_wide_env,
        layer="app-wide dotenv overrides",
        real_location=(
            "<platform config home>/"
            f"{spec.kit.spec.app_name}/{spec.kit.spec.app_wide_env_filename}"
        ),
        values=spec.app_wide_values,
    )

    storage_root = None
    index_path = config_home / spec.kit.spec.index_filename
    if spec.uses_storage:
        storage_root = root / "storages" / spec.storage_name
        storage_root.mkdir(parents=True, exist_ok=True)
        _write_env_layer(
            path=storage_root / spec.kit.spec.storage_env_filename,
            layer="storage-local dotenv overrides",
            real_location=(
                f"<selected storage root>/{spec.kit.spec.storage_env_filename}"
            ),
            values=spec.storage_values or {},
        )
        _write_storage_index(
            path=index_path,
            storage_name=spec.storage_name,
            storage_root=storage_root,
            app_name=spec.kit.spec.app_name,
            index_filename=spec.kit.spec.index_filename,
        )

    env_path = root / ".env"
    _write_sourceable_env(
        path=env_path,
        spec=spec,
        xdg_config_home=xdg_config_home,
        index_path=index_path,
        storage_root=storage_root,
    )
    return env_path


def _example_app_specs() -> tuple[ExampleAppSpec, ...]:
    """Return dev-only example specs from source or installed examples."""
    example_src_text = str(EXAMPLE_SRC)
    if example_src_text not in sys.path:
        sys.path.insert(0, example_src_text)
    from apprc_example_apps import example_app_specs

    return example_app_specs()


def _write_sourceable_env(
    *,
    path: Path,
    spec: ExampleAppSpec,
    xdg_config_home: Path,
    index_path: Path,
    storage_root: Path | None,
) -> None:
    """Write the arbitrary user-owned env file for one example."""
    values = {
        "XDG_CONFIG_HOME": str(xdg_config_home.resolve()),
        **dict(spec.explicit_values),
    }
    if spec.uses_storage:
        storage_env_key = spec.kit.spec.require_storage_env_key()
        if storage_root is None:
            raise RuntimeError(f"{spec.name} requires a storage root.")
        values[storage_env_key] = str(storage_root.resolve())
        values[spec.kit.spec.index_env_key] = str(index_path.resolve())

    comment = [
        "# Generated by python -m apprc_dev.example_apps.bootstrap.",
        "# AppRC layer: explicit env file or shell-exported values.",
        "# AppRC does not choose a location for this file in real apps.",
        "# Source it manually, for example: set -a; source .env; set +a",
        f"# Example command: {spec.kit.spec.config_command_name()} config doctor",
        "",
    ]
    path.write_text(
        "\n".join(comment + _dotenv_lines(values)) + "\n",
        encoding="utf-8",
    )


def _write_env_layer(
    *,
    path: Path,
    layer: str,
    real_location: str,
    values: Mapping[str, str],
) -> None:
    """Write one AppRC-managed dotenv layer with explanatory comments."""
    path.parent.mkdir(parents=True, exist_ok=True)
    comment = [
        "# Generated by python -m apprc_dev.example_apps.bootstrap.",
        f"# AppRC layer: {layer}.",
        f"# Bootstrapped checkout path: {path.resolve()}",
        f"# Real app location: {real_location}",
        "",
    ]
    path.write_text(
        "\n".join(comment + _dotenv_lines(values)) + "\n",
        encoding="utf-8",
    )


def _write_storage_index(
    *,
    path: Path,
    storage_name: str,
    storage_root: Path,
    app_name: str,
    index_filename: str,
) -> None:
    """Write a named-storage TOML index with explanatory comments."""
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(
        [
            "# Generated by python -m apprc_dev.example_apps.bootstrap.",
            "# AppRC layer: named-storage TOML index.",
            f"# Bootstrapped checkout path: {path.resolve()}",
            f"# Real app location: <platform config home>/{app_name}/{index_filename}",
            "",
            f"[storages.{storage_name}]",
            f"root = {json.dumps(str(storage_root.resolve()))}",
            "",
        ]
    )
    path.write_text(text, encoding="utf-8")


def _dotenv_lines(values: Mapping[str, str]) -> list[str]:
    """Return deterministic dotenv assignment lines."""
    return [
        f"{key}={json.dumps(value)}" for key, value in sorted(values.items())
    ]


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments for the bootstrap helper.

    :param argv: Optional argument vector used by tests.
    :return: Parsed command namespace.
    """
    parser = argparse.ArgumentParser(
        description="Bootstrap repository-local AppRC example app files.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove existing example sandboxes before writing files.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=ROOT,
        help="Repository root where .apprc-example* directories are written.",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Run the example bootstrap helper.

    :param argv: Optional argument vector used by tests.
    :return: Process exit code.
    """
    args = parse_args(argv)
    env_files = bootstrap_example_apps(
        repo_root=args.repo_root,
        clean=args.clean,
    )
    print("Bootstrapped AppRC example files:")
    for env_file in env_files:
        print(f"  {env_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
