"""Generate the metadata-only terminal distribution from the root project."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[3]
TERMINAL = Path(__file__).resolve().parent / "terminal"


def generated_files() -> dict[Path, str]:
    """Read shared metadata once and render independently buildable wrapper files.

    :return: Generated paths and their exact expected contents.
    """
    project = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]
    lines = [
        "# > Generated by src/apprc_dev/packaging/terminal_metadata.py.",
        "[build-system]",
        'requires = ["setuptools>=82"]',
        'build-backend = "setuptools.build_meta"',
        "",
        "[project]",
        'name = "apprc"',
    ]
    for key in (
        "version",
        "description",
        "requires-python",
        "license",
        "keywords",
        "classifiers",
    ):
        lines.append(f"{key} = {json.dumps(project[key])}")
    lines += [
        'readme = {file = "README.md", content-type = "text/markdown"}',
        'license-files = ["LICENSE"]',
        "authors = ["
        + ", ".join(
            "{"
            + ", ".join(
                f"{key} = {json.dumps(value)}" for key, value in author.items()
            )
            + "}"
            for author in project["authors"]
        )
        + "]",
        "dependencies = "
        + json.dumps(
            [
                f"apprc-core=={project['version']}",
                "typer",
                "rich",
                "prompt-toolkit>=3.0,<4",
                "textual",
            ]
        ),
        "",
        "[project.urls]",
        *(
            f"{key} = {json.dumps(value)}"
            for key, value in project["urls"].items()
        ),
        "",
        "[project.scripts]",
        'apprc = "apprc.__main__:main"',
        "",
        "[tool.setuptools]",
        "packages = []",
        "py-modules = []",
        "",
    ]
    return {
        TERMINAL / "pyproject.toml": "\n".join(lines),
        TERMINAL / "README.md": (ROOT / "README.pypi.md").read_text(),
        TERMINAL / "LICENSE": (ROOT / "LICENSE").read_text(),
    }


def main() -> None:
    """Write wrapper metadata or reject stale generated files with ``--check``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in generated_files().items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit(f"Stale generated metadata: {path.name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
